name: Build
on: workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: unzip ish-AOK-508.zip
      - run: brew install meson ninja llvm
      - run: meson build && cd build && ninja
      - run: mkdir Payload && find . -name *.app -exec cp -r {} Payload \; && zip -r iSH-AOK.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: iSH-AOK.ipa
          path: iSH-AOK.ipa
